### ISSUE TITLE
 JavaException: Sorry, I was expecting a discrete data set.

### ISSUE THREAD

**Issue by Angela446-lgtm** [bd2kccd/PyTetrad#101]
My dataset is consists of 7000 patients and 121 variables and and would like to apply the pc algorithm so I choose
algoId = 'pc-all', dfs = df, testId = 'chi-square-test'. All my variables are discrete. Please have a look 
      varibele1 variable2    variable3 variable4  ...  variable5 variable6 variable7  variable8 ....etc
0             18             11           15       9  ...         0.0      0.0             3.0           3.0
1             17             97           47      93  ...         0.0      0.0             3.0           3.0
2             14             56           30      60  ...         0.0      0.0             1.0           2.0

When I run the code this is the error that I take:
JavaException: Sorry, I was expecting a discrete data set.
Exception in thread "Thread-0" java.lang.IllegalArgumentException: Sorry, I was expecting a discrete data set.
	at edu.cmu.tetrad.data.DataUtils.getDiscreteDataSet(DataUtils.java:1888)
	at edu.cmu.tetrad.algcomparison.independence.ChiSquare.getTest(ChiSquare.java:30)
	at edu.cmu.tetrad.algcomparison.algorithm.oracle.pattern.PcAll.search(PcAll.java:91)

Could you please help me?

**Comment by chirayukong** [comment]
If you could convert the last two columns' data to be integer (from 3.0 to 3), then the py-causal should work like a charm. :-)

**Comment by Angela446-lgtm** [comment]
Thank you.

**Comment by jmcoftrindade** [comment]
I'm having the same problem, even after explicitly converting the dataframe to ints with df.astype(int).

I'm sure all values are integers (int64), so did the suggested solution solved the problem?


--- Code ---

'''
df reads a file like this (with more lines obviously)

Cancer,Dyspnoea,Pollution,Smoker,Xray
1,1,0,1,1
1,1,0,1,0
1,1,0,1,1
1,1,0,1,1
'''
# explicitly make sure that all values are ints
int_df = df.astype(int)

ind_test = chi-square-test

int_df = df.astype(int)

tetrad.run(algoId = 'pc-all', dfs = int_df, testId = ind_test,
               colliderDiscoveryRule = 1, fasRule = 2, depth = 2,
               stableFAS = True ,conflictRule = 1, concurrentFAS = True,
               useMaxPOrientationHeuristic = True, verbose = True)
